server:
  port: 9527
spring:
  application:
    name: cloud-gateway-gateway9527
  #配置gateway相关信息
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址(未开启动态路由的配置)
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址（开启了动态路由的配置）lb是一种路由协议
          predicates:
            - Path=/pay/create/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-provider-payment #匹配后提供服务的路由地址（开启了动态路由的配置）
          predicates:
            - Path=/pay/get/**